### ISSUE TITLE
AI 가 공을 안주고 계속 혼자 튕기는 경우가 있음.

### ISSUE THREAD

**Issue by aucshow-wjb** [gorisanson/pikachu-volleyball#11]
절~대 안줌
![ppp](https://user-images.githubusercontent.com/110958823/191631897-daa07dba-b9df-4f84-b213-9a1493750791.gif)

**Comment by gorisanson** [comment]
@aucshow-wjb 
제보 감사합니다! 영상까지 찍어서 올려주셨네요. 너무 감사합니다!

이에 대한 제보를 전에 다른 분을 통해 받은 적이 있어 이에 대해 조사를 한 적이 있습니다. 그 조사 결과, 원조 피카츄 배구에도 동일한 상황에서 동일한 버그가 발생한다는 것을 알게 되었습니다. [치트 엔진](https://www.cheatengine.org/)으로 원조 피카츄 게임 내에서의 공의 좌표, 공의 속도, 왼편 피카츄의 좌표, computerBoldness (https://github.com/gorisanson/pikachu-volleyball/blob/4e397614d7efbde92de4a868d5cb9d95da90521c/src/resources/js/physics.js#L200-L213 소스 참조) 아마 이 정도의 값들을 웹 버전에서 버그 발생했을 때의 수치와 동일하게 설정했던 것으로 기억하는데, 그렇게 하니 원조 피카츄 버전에서도 동일한 현상이 나타나는 것을 관찰할 수 있었습니다. 아래는 당시 찍었던 영상입니다. 동일한 버그가 재현된 것을 관찰할 수 있습니다.

https://user-images.githubusercontent.com/38519601/191703933-ec3dc138-dbc7-4c25-83a7-22e6d2c40808.mp4

https://user-images.githubusercontent.com/38519601/191704556-77ad56e5-9e44-4058-aa84-8ebf602c6f70.mp4

[웹 버전 피카츄 배구](https://gorisanson.github.io/pikachu-volleyball/ko/)는 원조 피카츄 배구를 리버스 엔지니어링한 결과로 나온 것이라 버그 또한 기본적으로 동일하게 재현이 됩니다.

위 버그에 대해서는 웹 버전에서만이라도 버그 패치를 할까 말까 고민을 했었습니다. 고민의 결과, 원조 피카츄 배구와 동일하게 버그 또한 그대로 두자고 결론을 내렸습니다. 자주 마주치는 버그가 아니기에 게임 플레이에 지장을 주는 정도는 아니라 판단하였고, 가끔 마주치게 되는 경우는 '오 이런 경우도 있네?'하고 웃고 지나갈 수 있는 기회가 될거라, 그리고 원조 버전에서도 동일한 버그를 겪었던 분이라면 원조버전에 대한 향수를 불러일으키는 기회가 될 수 있겠다 생각했습니다.

원조버전에서 발생한 동일한 버그를 영상으로 찍어서 유튜브에 올린 분이 계시더군요. (전에 저에게 이 버그를 제보해주셨다는 분이 이 영상의 존재 또한 저에게 알려주셨습니다.) 아래 링크는 해당 유튜브 영상의 링크입니다. (영상 게시 일자가 2016년 2월 15일입니다. 웹 버전 공개일인 2020년 3월 26일보다 약 4년 정도 앞선 때이므로, 원조 피카츄 배구 게임에서 발생한 버그를 찍은 영상이라는 것을 알 수 있습니다.)
https://youtu.be/L-xlQBuXAAA

다시 한번 소중한 제보 감사드립니다!

**Comment by aucshow-wjb** [comment]
완전 최고십니다 덕분에 점심에 온라인으로 잘 놀고 있습니다!
감사합니다~
