### ISSUE TITLE
fix typo

### ISSUE THREAD

**Issue by helpingstar** [gorisanson/pikachu-volleyball#21]
https://github.com/gorisanson/pikachu-volleyball/blob/8b4bd7d43fec469cb23e29516c6ed96c78286d39/src/resources/js/physics.js#L226-L234

`/** @type {number} x coord of expected lang point */ `

위의 주석에서 
"lang" 이란 부분이 "landing", 혹은 "land"을 쓰려다 나온 오타인 것으로 보입니다.
오타가 맞다면 PR을 하겠습니다.

From the comment above
The "lang" part appears to be a typo that occurred when trying to use "landing" or "land."
If the typo is correct, I will give you a PR.

**Comment by gorisanson** [comment]
오 감사합니다! 오타가 맞습니다. landing을 쓰려던 것이었습니다. PR 기다리겠습니다!
