### ISSUE TITLE
코드 구조와 최적화 관련한 건의

### ISSUE THREAD

**Issue by helpingstar** [gorisanson/pikachu-volleyball#24]
영어 실력이 부족하여 긴 글이기에 한글로 작성합니다.

물론 피카츄배구가 현재 잘 작동되고 있으며, 최대속도 30FPS 안에 연산을 마치면 게임 실행에 문제가 없기 때문에 해당 내용도 크게 문제는 없습니다. 그래도 고려해봄직 하다 생각하여 작성합니다.

`calculateExpectedLandingPointXFor` 함수는 공의 착지 위치로 기대되는(예상되는) x 값을 계산하는 함수입니다.

위 함수는 두 곳에서 실행됩니다.

아래는 `physicsEngine` 함수내부이고
https://github.com/gorisanson/pikachu-volleyball/blob/d8ec117e550f8b1ee047b0ad0c95be54df52213c/src/resources/js/physics.js#L323

아래는 `processCollisionBetweenBallAndPlayer`의 내부입니다. 
(`processCollisionBetweenBallAndPlayer`는 `physicsEngine` 함수에 의해 실행)
https://github.com/gorisanson/pikachu-volleyball/blob/d8ec117e550f8b1ee047b0ad0c95be54df52213c/src/resources/js/physics.js#L730

`calculateExpectedLandingPointXFor` 함수에서 저장된 `ball.expectedLandingPointX`는

https://github.com/gorisanson/pikachu-volleyball/blob/d8ec117e550f8b1ee047b0ad0c95be54df52213c/src/resources/js/physics.js#L787

 `letComputerDecideUserInput`, `decideWhetherInputPowerHit`(`letComputerDecideUserInput` 에 의해 실행) 에 의해 **사용**됩니다. 즉 컴퓨터의 행동을 정하기 위한 함수입니다.

https://github.com/gorisanson/pikachu-volleyball/blob/d8ec117e550f8b1ee047b0ad0c95be54df52213c/src/resources/js/physics.js#L496-L504
501-504줄을 보면 컴퓨터일 경우만 판단하도록 되어 있습니다(당연하지만)

그렇다면 `calculateExpectedLandingPointXFor` 함수는 컴퓨터가 없다면 실행할 필요가 없게 됩니다. 그런데 현재는 두 플레어가 사람이어도 공의 기대 x위치를 계산하게 되는데 이때는 필요없는 연산입니다.

그리하여 아래와 같은 코드를 넣으면 될 것 같지만

```javascript
    if (player1.isComputer === true || player2.isComputer === true){
      calculateExpectedLandingPointXFor(ball);
    }
```
`processCollisionBetweenBallAndPlayer` 함수는 두 플레이어의 정보를 인자로 받지 않습니다.
하지만 해당 함수는 무조건 마지막에 `calculateExpectedLandingPointXFor(ball);` 를 실행합니다.

앞에서 말씀드렸다시피 `processCollisionBetweenBallAndPlayer` 함수는 오직`physicsEngine` 함수에 의해서만 실행되는데 `physicsEngine` 함수는 player1, player2를 받기 때문에

(물론 player1, player2를 인자로 전달해도 되지만 실행되는 장소가 한 곳이고, 코드가 너무 지저분해지기 때문에 아래가 낫다 생각했습니다.)

`processCollisionBetweenBallAndPlayer` 의 마지막줄인 `calculateExpectedLandingPointXFor` 를 실행하는 코드를 지우고

https://github.com/gorisanson/pikachu-volleyball/blob/d8ec117e550f8b1ee047b0ad0c95be54df52213c/src/resources/js/physics.js#L309-L323

를 아래와 같이 고치고 (맨 아래줄)

```javascript
  for (let i = 0; i < 2; i++) {
    if (i === 0) {
      player = player1;
      theOtherPlayer = player2;
    } else {
      player = player2;
      theOtherPlayer = player1;
    }

    // FUN_00402d90 omitted
    // FUN_00402810 omitted
    // this javascript code is refactored not to need above two function except for
    // a part of FUN_00402d90:
    // FUN_00402d90 include FUN_004031b0(calculateExpectedLandingPointXFor)
    if (player1.isComputer === true || player2.isComputer === true){
      calculateExpectedLandingPointXFor(ball);
    }
```
https://github.com/gorisanson/pikachu-volleyball/blob/d8ec117e550f8b1ee047b0ad0c95be54df52213c/src/resources/js/physics.js#L351-L364

부분을 아래와 같이 고치면 됩니다.
(`processCollisionBetweenBallAndPlayer` 에서 코드를 지웠기 때문에 함수 종료 후 바로 `calculateExpectedLandingPointXFor` 실행)

```javascript
    if (isHappened === true) {
      if (player.isCollisionWithBallHappened === false) {
        processCollisionBetweenBallAndPlayer(
          ball,
          player.x,
          userInputArray[i],
          player.state
        );
        if (player1.isComputer === true || player2.isComputer === true){
          calculateExpectedLandingPointXFor(ball);
        }
        player.isCollisionWithBallHappened = true;
      }
    } else {
      player.isCollisionWithBallHappened = false;
    }
  }
```

제가 고려하지 못했거나 놓친 부분이 있을 수 있기 때문에 issue 탭에 말씀드립니다. 아마 이미 아셨을 것이라 생각되지만 혹시나 하여 말씀드립니다.

괜찮다면 PR 하겠습니다.

**Comment by gorisanson** [comment]
@helpingstar

안녕하세요. 우성님. 답변이 늦어 죄송합니다. 디테일하게 설명해주시고 제안해주셔서 너무나 감사합니다. 우성님이 말씀해주신 내용은 모두 정확하고 타당하지만, 아쉽게도 이번 제안을 받아들이는 어렵겠습니다.

[`physics.js`](https://github.com/gorisanson/pikachu-volleyball/blob/d8ec117e550f8b1ee047b0ad0c95be54df52213c/src/resources/js/physics.js) 파일 그러니까 [물리 엔진](https://github.com/gorisanson/pikachu-volleyball/blob/d8ec117e550f8b1ee047b0ad0c95be54df52213c/README.ko.md#%EA%B2%8C%EC%9E%84-%EA%B5%AC%EC%A1%B0) 부분은 리버스 엔지니어링의 핵심 부분입니다. `physics.js` 파일에 대해 저는 다음과 같은 기준을 따르기 위해 개인적으로 노력했습니다.

- 최대한 원본 게임의 물리 엔진 소스 구조를 그대로 따른다.
- 불가피하게 다르게 만들어야할 경우, 충분한 주석을 두어 설명한다. (예시: [`INFINITE_LOOP_LIMIT`](https://github.com/gorisanson/pikachu-volleyball/blob/d8ec117e550f8b1ee047b0ad0c95be54df52213c/src/resources/js/physics.js#L53-L64))

위와 같은 기준을 따르려고한 이유는 원조 피카츄 배구가 어떻게 만들어졌는가 알고 싶어하는 분이 있을 경우, `physics.js` 코드를 보면서 원조 게임의 소스 코드를 충분히 파악할 수 있기를 저는 바라기 때문입니다.

우성님이 제안해주신 내용은 최적화 관점에서는 매우 타당하나, 제가 생각하기에는 소스 구조를 바꾸어야하는 것을 감수할 정도로 불가피하게 필요한 내용은 아닌 것으로 여겨집니다. 해당 최적화를 도입하지 않는다고해서 게임 동작에 지장이 생길 가능성은 사실상 없다고 보이기 때문입니다.

너무 감사한 제안 아쉽게 받아들이지 못해 죄송합니다.

---

PS. 우성님의 저장소인 [pika-zoo](https://github.com/helpingstar/pika-zoo)와 관련해서는 해당 최적화가 의미를 가질 수도 있을 것으로 생각됩니다. (게임을 조금이라도 빨리 돌릴 수 있어야 그만큼 RL 훈련에 필요한 시간이 줄어들지 않을까 막연한 생각(?)입니다.) 그렇다면 우성님 저장소에서 해당 부분 최적화를 진행하시고 만약 필요하다고 생각되신다면 최적화의 이유에 대해 주석으로 설명해주시면 어떨까 생각이듭니다.

**Comment by helpingstar** [comment]
@gorisanson 
관련하여 타당여부까지 확인해주신 것만으로도 감사드립니다. 저장소 특성상 원본을 최대한 유지하는 성격이 더 크기도 하고, 사실 현재 게임 진행에 있어서 지금도 전혀 문제가 없고 컴퓨터 사양들은 오르는 일 밖에 남지 않았으니 앞으로도 문제가 될 일이 없을 것이라 생각됩니다. 말씀해주신 사안에 대해서 충분히 공감합니다. 확인해주셔서 감사드립니다. 죄송하다고 말씀 안하셔도 됩니다. 코드를 더 제대로 이해했다는 사실에 만족합니다! issue는 close하겠습니다.
