### ISSUE TITLE
Just to say thanks and congratulate you

### ISSUE THREAD

**Issue by rebrec** [gorisanson/pikachu-volleyball#5]
Just leaving you a message to say thank you.
Your implementation seems the same as the original one
Happy to see that this game is still alive thanks to you

Cheers

**Comment by gorisanson** [comment]
@rebrec 
I’m glad to hear that you are happy to see that this game is still alive:) Your saying assure me that my work and effort for reverse engineering the Pikachu Volleyball game and porting it to web has been meaningful to someone as well as to me. Thank you for cheering me up!

**Comment by zzwonder** [comment]
I also want to thank you for reproducing this game! It brought my great childhood memories!

**Comment by gorisanson** [comment]
@zzwonder Thank you for saying so! I'm happy to hear that!
