### ISSUE TITLE
Trouble building on main branch

### ISSUE THREAD

**Issue by Pxter7777** [gorisanson/pikachu-volleyball#6]
Hi,
Demo on Windows 10 x64, VSCode's Live Server and Firefox.
gh-pages branch works fine.

But I had trouble building on main branch.
using npm v8.1.2
`> npm install`
`> npm run build`
Used Live Server to test ./dist/en/index.html
After pressing Play button it stuck like this.
![圖片](https://user-images.githubusercontent.com/81604534/144746493-09d8ddc5-c9dd-411a-abe2-7ec4fcca806f.png)
I guess the assets failed loading, not sure why.
Another thing is I got `80.bundle.js` instead of `511.bundle.js`, and `80.bundle.js` file size is somehow much bigger than `511.bundle.js`.
I'm new to front end and Webpack, maybe I missed something?

**Comment by gorisanson** [comment]
@Pxter7777 
Can you try with Node v14.18.2 and npm v6.14.15?

**Comment by Pxter7777** [comment]
@gorisanson 
Yeah, simply changed to Node v14.18.2 and npm v6.14.15, re-installed the modules.
And the problem is fixed.

Thanks for your help and your awesome projects.

Wish you Luck!
