### ISSUE TITLE
Uncaught TypeError: Cannot read properties of null (reading 'baseTexture')

### ISSUE THREAD

**Issue by ghost** [gorisanson/pikachu-volleyball#9]
Hello.
I'm running this on Windows 10.
I use nodejs 14.18.2 and npm 6.14.15.

Every time I try to start a game, the following log is displayed on the console and does not work.
I tried various methods, but they didn't fix it.
Help.
![image](https://user-images.githubusercontent.com/78199903/159910525-750af42b-0b79-4546-ad59-09bcfa63e75f.png)

**Comment by gorisanson** [comment]
Could you please tell me the procedure you followed to start the game?
Did you do like the following on your terminal?

```
git clone https://github.com/gorisanson/pikachu-volleyball.git
cd ./pikachu-volleyball
npm install
npm run build
http-server dist
```

And then connect to the `http://localhost:8080` on your browser.

To execute the last line `http-server dist`,  [http-server](https://www.npmjs.com/package/http-server) should have been already installed.  You can install [http-server](https://www.npmjs.com/package/http-server) by running
```
npm install --global http-server
```

**Comment by ghost** [comment]
I tried that method, but it didn't change.
![image](https://user-images.githubusercontent.com/78199903/159916432-54103780-bce4-4c92-8765-d9c3854ff67a.png)

**Comment by gorisanson** [comment]
@Jaemin0299 

Could you try the following?

- Remove `node_modules` folder and `package-lock.json` file, and then `npm install` again. Check if the game is executed normally.

If the method above does not work, please try the following.
- Remove `node_modules` folder and `package-lock.json` file first, and then run the following commands in your terminal:
```
git pull
git switch main-with-package-lock
npm install
npm run build
http-server dist
``` 
 `main-with-package-lock` branch includes `package-lock.json` file which is the same as on my local machine.

**Comment by gorisanson** [comment]
@Jaemin0299 Have you run the game successfully?

**Comment by ghost** [comment]
Yes, it worked well without any problems. Thank you for your help.

**Comment by gorisanson** [comment]
@Jaemin0299 Which solution worked? First one? Or second one?

**Comment by ghost** [comment]
Second one

**Comment by gorisanson** [comment]
@Jaemin0299
Thank you for replying me. I did not include `package-lock.json` to `main` branch because I do not want 
[the contribution graph on this repo](https://github.com/gorisanson/pikachu-volleyball/graphs/contributors) to be polluted by the line counts of `package-lock.json`. But, as you know, `package-lock.json` is recommended to be included in git commits. I think I should find a better way to solve these problems. Thank you!

**Comment by gorisanson** [comment]
Now I have included `package-lock.json` to `main` branch using [some method by which `package-lock.json` not to be counted as contributions](https://stackoverflow.com/a/44286485/8581025). So I have decided to remove `main-with-package-lock` branch which now have become just a copy of `main` branch.
